package com.woleapp.netpos.contactless.model.payment.transactions

data class Transaction(
    val STAN: String,
    val accountType: String,
    val agentName: String,
    val amount: Double,
    val cardHolder: String,
    val cardLabel: String,
    val channel: String,
    val dateCreated: String,
    val details: String,
    val maskedPan: String,
    val merchantId: String,
    val merchantName: String,
    val partnerId: String,
    val payer_account_name: String,
    val payer_account_number: String,
    val payer_bank_code: String,
    val recipient_account_number: String,
    val responseCode: String?,
    val responseMessage: String,
    val rrn: String,
    val source: String,
    val terminalId: String,
    val time: String,
    val transactionTime: String,
    val transactionType: String,
    val transaction_reference: String,
    val type: String,
)
