.class public Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;
.super Ljava/lang/Object;
.source "FeederTxnStatDefinition.java"


# static fields
.field public static final ACK_WAIT_MS:Lcom/sleepycat/je/utilint/StatDefinition;

.field public static final ACK_WAIT_MS_DESC:Ljava/lang/String; = "Total MS waited for acks."

.field public static final ACK_WAIT_MS_NAME:Ljava/lang/String; = "ackWaitMS"

.field public static final GROUP_DESC:Ljava/lang/String; = "FeederTxns statistics"

.field public static final GROUP_NAME:Ljava/lang/String; = "FeederTxns"

.field public static final LAST_COMMIT_TIMESTAMP:Lcom/sleepycat/je/utilint/StatDefinition;

.field public static final LAST_COMMIT_TIMESTAMP_DESC:Ljava/lang/String; = "The commit timestamp of the last committed transaction on the master, or 0 if not known or this node is not the master."

.field public static final LAST_COMMIT_TIMESTAMP_NAME:Ljava/lang/String; = "lastCommitTimestamp"

.field public static final LAST_COMMIT_VLSN:Lcom/sleepycat/je/utilint/StatDefinition;

.field public static final LAST_COMMIT_VLSN_DESC:Ljava/lang/String; = "The VLSN of the last committed transaction on the master, or 0 if not known or this node is not the master."

.field public static final LAST_COMMIT_VLSN_NAME:Ljava/lang/String; = "lastCommitVLSN"

.field public static final TOTAL_TXN_MS:Lcom/sleepycat/je/utilint/StatDefinition;

.field public static final TOTAL_TXN_MS_DESC:Ljava/lang/String; = "The total elapsed MS across all txns from transaction start to end."

.field public static final TOTAL_TXN_MS_NAME:Ljava/lang/String; = "totalTxnMS"

.field public static final TXNS_ACKED:Lcom/sleepycat/je/utilint/StatDefinition;

.field public static final TXNS_ACKED_DESC:Ljava/lang/String; = "Number of Transaction ack\'d."

.field public static final TXNS_ACKED_NAME:Ljava/lang/String; = "txnsAcked"

.field public static final TXNS_NOT_ACKED:Lcom/sleepycat/je/utilint/StatDefinition;

.field public static final TXNS_NOT_ACKED_DESC:Ljava/lang/String; = "Number of Transactions not Ack\'d."

.field public static final TXNS_NOT_ACKED_NAME:Ljava/lang/String; = "txnsNotAcked"

.field public static final VLSN_RATE:Lcom/sleepycat/je/utilint/StatDefinition;

.field public static final VLSN_RATE_DESC:Ljava/lang/String; = "A moving average of the rate replication data is being generated by the master, in VLSNs per minute, or 0 if not known or this node is not the master."

.field public static final VLSN_RATE_NAME:Ljava/lang/String; = "vlsnRate"


# direct methods
.method static constructor <clinit>()V
    .locals 4

    .line 31
    new-instance v0, Lcom/sleepycat/je/utilint/StatDefinition;

    const-string/jumbo v1, "txnsAcked"

    const-string v2, "Number of Transaction ack\'d."

    invoke-direct {v0, v1, v2}, Lcom/sleepycat/je/utilint/StatDefinition;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    sput-object v0, Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;->TXNS_ACKED:Lcom/sleepycat/je/utilint/StatDefinition;

    .line 40
    new-instance v0, Lcom/sleepycat/je/utilint/StatDefinition;

    const-string/jumbo v1, "txnsNotAcked"

    const-string v2, "Number of Transactions not Ack\'d."

    invoke-direct {v0, v1, v2}, Lcom/sleepycat/je/utilint/StatDefinition;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    sput-object v0, Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;->TXNS_NOT_ACKED:Lcom/sleepycat/je/utilint/StatDefinition;

    .line 49
    new-instance v0, Lcom/sleepycat/je/utilint/StatDefinition;

    const-string/jumbo v1, "totalTxnMS"

    const-string v2, "The total elapsed MS across all txns from transaction start to end."

    invoke-direct {v0, v1, v2}, Lcom/sleepycat/je/utilint/StatDefinition;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    sput-object v0, Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;->TOTAL_TXN_MS:Lcom/sleepycat/je/utilint/StatDefinition;

    .line 58
    new-instance v0, Lcom/sleepycat/je/utilint/StatDefinition;

    const-string v1, "ackWaitMS"

    const-string v2, "Total MS waited for acks."

    invoke-direct {v0, v1, v2}, Lcom/sleepycat/je/utilint/StatDefinition;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    sput-object v0, Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;->ACK_WAIT_MS:Lcom/sleepycat/je/utilint/StatDefinition;

    .line 68
    new-instance v0, Lcom/sleepycat/je/utilint/StatDefinition;

    sget-object v1, Lcom/sleepycat/je/utilint/StatDefinition$StatType;->CUMULATIVE:Lcom/sleepycat/je/utilint/StatDefinition$StatType;

    const-string v2, "lastCommitVLSN"

    const-string v3, "The VLSN of the last committed transaction on the master, or 0 if not known or this node is not the master."

    invoke-direct {v0, v2, v3, v1}, Lcom/sleepycat/je/utilint/StatDefinition;-><init>(Ljava/lang/String;Ljava/lang/String;Lcom/sleepycat/je/utilint/StatDefinition$StatType;)V

    sput-object v0, Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;->LAST_COMMIT_VLSN:Lcom/sleepycat/je/utilint/StatDefinition;

    .line 79
    new-instance v0, Lcom/sleepycat/je/utilint/StatDefinition;

    sget-object v1, Lcom/sleepycat/je/utilint/StatDefinition$StatType;->CUMULATIVE:Lcom/sleepycat/je/utilint/StatDefinition$StatType;

    const-string v2, "lastCommitTimestamp"

    const-string v3, "The commit timestamp of the last committed transaction on the master, or 0 if not known or this node is not the master."

    invoke-direct {v0, v2, v3, v1}, Lcom/sleepycat/je/utilint/StatDefinition;-><init>(Ljava/lang/String;Ljava/lang/String;Lcom/sleepycat/je/utilint/StatDefinition$StatType;)V

    sput-object v0, Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;->LAST_COMMIT_TIMESTAMP:Lcom/sleepycat/je/utilint/StatDefinition;

    .line 91
    new-instance v0, Lcom/sleepycat/je/utilint/StatDefinition;

    const-string/jumbo v1, "vlsnRate"

    const-string v2, "A moving average of the rate replication data is being generated by the master, in VLSNs per minute, or 0 if not known or this node is not the master."

    invoke-direct {v0, v1, v2}, Lcom/sleepycat/je/utilint/StatDefinition;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    sput-object v0, Lcom/sleepycat/je/rep/stream/FeederTxnStatDefinition;->VLSN_RATE:Lcom/sleepycat/je/utilint/StatDefinition;

    return-void
.end method

.method public constructor <init>()V
    .locals 0

    .line 22
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
