package com.woleapp.netpos.contactless.util

import java.util.*

object AppConstants {
    fun getGUID() = UUID.randomUUID().toString().replace("-", "")
    const val PERMISSION_REQUEST_CODE = 200
    const val LONG_150 = 150L
    const val STRING_QR_READ_RESULT_REQUEST_KEY = "STRING_QR_READ_RESULT_REQUEST_KEY"
    const val STRING_QR_READ_RESULT_BUNDLE_KEY = "STRING_QR_READ_RESULT_BUNDLE_KEY"
    const val STRING_LOADING_DIALOG_TAG = "STRING_LOADING_DIALOG_TAG"
    const val STRING_QR_RESPONSE_MODAL_DIALOG_TAG = "STRING_QR_RESPONSE_MODAL_DIALOG_TAG"
    const val STRING_TAG_JAVASCRIPT_INTERFACE_TAG = "Android"
    const val QR_TRANSACTION_RESULT_REQUEST_KEY = "QR_TRANSACTION_RESULT_REQUEST_KEY"
    const val QR_TRANSACTION_RESULT_BUNDLE_KEY = "QR_TRANSACTION_RESULT_BUNDLE_KEY"
    const val SAVE_QR_TRANS_TO_DB = "SAVE_QR_TRANS_TO_DB====>"
    const val IS_QR_TRANSACTION = "IS_QR_TRANSACTION"
    const val QR_TRANSACTION_POST_REQUEST_PAYLOAD = "QR_TRANSACTION_POST_REQUEST_PAYLOAD"
    const val STRING_QR_TRANSACTION_DATE_TIME_FORMAT = "yyyy-MM-dd hh:mm a"
    const val WRITE_PERMISSION_REQUEST_CODE = 113
    const val PIN_BLOCK_RK = "PIN_BLOCK_RK"
    const val PIN_BLOCK_BK = "PIN_BLOCK_BK"
    const val STRING_ACCOUNT_NUMBER_LOOKUP_TAG = "STRING_ACCOUNT_NUMBER_LOOKUP_TAG"
    const val SAVED_ACCOUNT_NUM_SIGNED_UP = "SAVED_ACCOUNT_NUM_SIGNED_UP"
    const val SAVE_PHONE_NUMBER = "SAVE_PHONE_NUMBER"
    const val PAYMENT_WITH_QR_STRING = "PAYMENT_WITH_QR_STRING"
    const val SAVE_CUSTOMER_DATA = "SAVE_CUSTOMER_DATA"
    const val BUSINESS_NAME = "BUSINESS_NAME"
    const val FULL_NAME = "FULL_NAME"
    const val BUSINESS_ADDRESS = "BUSINESS_ADDRESS"
    const val PHONE_NUMBER = "PHONE_NUMBER"
    const val EMAIL_ADDRESS = "EMAIL_ADDRESS"
    const val WORKER_INPUT_FIREBASE_DEVICE_TOKEN_TAG = "WORKER_INPUT_FIREBASE_DEVICE_TOKEN_TAG"
    const val channelId = "NetPos"
    const val READ_PHONE_STATE_REQUEST_CODE = 101
    const val STRING_FIREBASE_INTENT_ACTION = "com.woleapp.netpos.FIREBASE_ACTION"
    const val TAG_NOTIFICATION_RECEIVED_FROM_BACKEND = "TAG_NOTIFICATION_RECEIVED_2"
    const val INT_FIREBASE_PENDING_INTENT_REQUEST_CODE = 772
    const val NOTIFICATION_ERROR = "NOTIFICATION_ERROR"
    const val WORKER_INPUT_PBT_TRANSACTION_TAG = "WORKER_INPUT_PBT_TRANSACTION_TAG"

}
