package com.woleapp.netpos.contactless.util

import java.util.*

object AppConstants {
    fun getGUID() = UUID.randomUUID().toString().replace("-", "")
    const val PERMISSION_REQUEST_CODE = 200
    const val STRING_QR_READ_RESULT_REQUEST_KEY = "STRING_QR_READ_RESULT_REQUEST_KEY"
    const val STRING_QR_READ_RESULT_BUNDLE_KEY = "STRING_QR_READ_RESULT_BUNDLE_KEY"
    const val STRING_LOADING_DIALOG_TAG = "STRING_LOADING_DIALOG_TAG"
    const val STRING_QR_RESPONSE_MODAL_DIALOG_TAG = "STRING_QR_RESPONSE_MODAL_DIALOG_TAG"
    const val STRING_TAG_JAVASCRIPT_INTERFACE_TAG = "Android"
    const val QR_TRANSACTION_RESULT_REQUEST_KEY = "QR_TRANSACTION_RESULT_REQUEST_KEY"
    const val QR_TRANSACTION_RESULT_BUNDLE_KEY = "QR_TRANSACTION_RESULT_BUNDLE_KEY"
    const val SAVE_QR_TRANS_TO_DB = "SAVE_QR_TRANS_TO_DB====>"
    const val QR_TRANSACTION_POST_REQUEST_PAYLOAD = "QR_TRANSACTION_POST_REQUEST_PAYLOAD"
    const val STRING_QR_TRANSACTION_DATE_TIME_FORMAT = "yyyy-MM-dd hh:mm a"
    const val WRITE_PERMISSION_REQUEST_CODE = 113
}
